### PR TITLE
update Istio per-route metrics

### PR DESCRIPTION
**Pull request by oaktowner**
One minor correction: Istio does collect per-route metrics.

Thanks!

### CODE REVIEW

**Comment by HPrinz** [comment]
Great, I didn't know that! Do you have link to the docs that shows that?

**Comment by oaktowner** [comment]
Ack! Our docs are incomplete! 

Listed here https://raw.githubusercontent.com/istio/istio/release-1.4/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
(see  method: request.method )

But I'll submit a PR over there to get it [here](https://istio.io/docs/reference/config/policy-and-telemetry/metrics/) as well:

BTW, I'll add one more commit bumping up our version number.

**Comment by oaktowner** [comment]
Please hold off on this for now -- this metric is turned _off_ be default right now and I'm researching why. Thanks for your patience!

**Comment by HPrinz** [comment]
Yes, sure! Take your time

**Pull request closed without merging**
